kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # this is to expose extra ports for NodePort. Ref:
  # - https://github.com/kubernetes-sigs/kind/pull/637
  # - https://github.com/kubernetes-sigs/kind/issues/99
  extraPortMappings:
  - containerPort: 30100
    hostPort: 30100
    protocol: TCP
  - containerPort: 30101
    hostPort: 30101
    protocol: TCP
  - containerPort: 30102
    hostPort: 30102
    protocol: TCP
- role: worker
- role: worker
- role: worker
