#
# Reference: https://k3d.io/usage/configfile/
#
apiVersion: k3d.io/v1alpha2
kind: Simple
name: k3s-cluster
servers: 1
agents: 3
kubeAPI:
  host: "localhost"
  hostIP: "127.0.0.1"
  hostPort: "6445"
image: rancher/k3s:v1.20.4-k3s1
network: k3s-network
token: superSecretToken
volumes:
  - volume: /my/host/path:/path/in/node
    nodeFilters:
      - server[0]
      - agent[*]
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
labels:
  - label: foo=bar
    nodeFilters:
      - agent[1]
env:
  - envVar: bar=baz
    nodeFilters:
      - server[0]
registries:
  create: true
  use:
    - k3d-myotherregistry:5000
  config: |
    mirrors:
      "my.company.registry":
        endpoint:
          - http://my.company.registry:5000
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    disableHostIPInjection: false
  k3s:
    extraServerArgs:
      - --tls-san=my.host.domain
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    gpuRequest: all